const DATA=[
{name:'Paracetamol',generic:'Paracetamol / Acetaminophen',manufacturer:'Common analgesic',form:'Tablet',tag:'Pain / Fever'},
{name:'Metformin',generic:'Metformin hydrochloride',manufacturer:'Prescription medicine',form:'Tablet',tag:'Diabetes'},
{name:'Amlodipine',generic:'Amlodipine',manufacturer:'Prescription medicine',form:'Tablet',tag:'Blood pressure'},
{name:'Cetirizine',generic:'Cetirizine hydrochloride',manufacturer:'Antihistamine',form:'Tablet',tag:'Allergy'},
{name:'Amoxicillin',generic:'Amoxicillin',manufacturer:'Antibiotic',form:'Capsule',tag:'Antibiotic'},
{name:'Ibuprofen',generic:'Ibuprofen',manufacturer:'NSAID',form:'Tablet',tag:'Pain / Inflammation'}
];
const interactions={
'aspirin|warfarin':{level:'Severe',text:'Demo warning: this combination may increase bleeding risk. Discuss with a qualified clinician/pharmacist.'},
'ibuprofen|aspirin':{level:'Moderate',text:'Demo warning: taking multiple NSAID medicines can increase side effects. Confirm with a professional.'},
'metformin|glimepiride':{level:'Mild',text:'Demo note: these medicines may be used together in diabetes care; monitoring is important.'}
};
function getProfile(){return JSON.parse(localStorage.getItem('medisafe_profile')||'null')||{name:'Guest User',email:'guest@example.com'}};
function path(){return location.pathname.split('/').pop()||'home.html'};
function esc(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function toast(t){let x=document.querySelector('.toast');if(!x){x=document.createElement('div');x.className='toast';document.body.appendChild(x)}x.textContent=t;setTimeout(()=>x.remove(),2500)}
function logout(){localStorage.removeItem('medisafe_logged');sessionStorage.removeItem('medisafe_logged');location.href='login.html'}
function nav(active){return `<aside class="sidebar" id="sidebar"><a class="brand" href="home.html"><span class="brand-mark">♡</span>MediSafe <b>AI</b></a><nav class="side-nav">
<a class="${active==='home'?'active':''}" href="home.html">⌂ <span>Home</span></a><a class="${active==='medicines'?'active':''}" href="medicines.html">◉ <span>My Medicines</span></a><a class="${active==='checker'?'active':''}" href="checker.html">⚕ <span>Interaction Check</span></a><a class="${active==='history'?'active':''}" href="history.html">◷ <span>Check History</span></a><a class="${active==='patient'?'active':''}" href="patient-history.html">▤ <span>Patient History</span></a><a class="${active==='profile'?'active':''}" href="my-profile.html">○ <span>My Profile</span></a><a class="${active==='settings'?'active':''}" href="settings.html">⚙ <span>Settings</span></a></nav><div class="side-bottom"><button onclick="logout()">Log out</button></div></aside>`}
function header(){const p=getProfile();return `<header class="app-header"><button class="mobile-side" id="openSide">☰</button><div></div><div class="header-actions"><button class="notif" onclick="toast('No new notifications')">♧</button><a class="user-chip" href="my-profile.html"><span class="avatar">${esc((p.name||'G')[0].toUpperCase())}</span><span>${esc(p.name)}</span></a></div></header>`}
function mobileBottom(active){return `<nav class="mobile-bottom"><a class="${active==='home'?'active':''}" href="home.html">⌂<small>Home</small></a><a class="${active==='medicines'?'active':''}" href="medicines.html">◉<small>Medicines</small></a><a class="${active==='checker'?'active':''}" href="checker.html">⚕<small>Check</small></a><a class="${active==='history'?'active':''}" href="history.html">◷<small>History</small></a><a class="${active==='profile'?'active':''}" href="my-profile.html">○<small>Profile</small></a></nav>`}
function shell(active,content){document.getElementById('app').innerHTML=`<div class="app-shell">${nav(active)}<div class="main-wrap">${header()}<main class="content">${content}</main></div></div>${mobileBottom(active)}`;document.getElementById('openSide').onclick=()=>document.getElementById('sidebar').classList.toggle('open')}
function home(){const p=getProfile();shell('home',`<div class="content-head"><div><span class="eyebrow">MEDISAFE AI</span><h1>Good morning, ${esc(p.name.split(' ')[0])} 👋</h1><p>Your medicine information, all in one calm place.</p></div></div><div class="dashboard-grid"><section><div class="soft-card welcome-card"><span class="tag">SMART MEDICINE COMPANION</span><h2>Stay informed about the medicines you use.</h2><p>Search your medicine, check an interaction or update your personal medicine cabinet.</p><a class="btn" href="medicines.html">Explore medicines →</a></div><div class="stat-grid"><div class="stat"><b>${getMeds().length}</b><span>Current medicines</span></div><div class="stat"><b>${getHistory().length}</b><span>Saved checks</span></div><div class="stat"><b>24/7</b><span>Easy access</span></div></div></section><aside class="soft-card"><span class="eyebrow">QUICK ACTIONS</span><h3>What do you want to do?</h3><div class="quick-grid"><a class="quick" href="medicines.html"><strong>⌕ Search</strong><small>Find medicine info</small></a><a class="quick" href="checker.html"><strong>⚕ Check</strong><small>Review interactions</small></a><a class="quick" href="patient-history.html"><strong>＋ Add</strong><small>Add a medicine</small></a><a class="quick" href="history.html"><strong>◷ History</strong><small>See previous checks</small></a></div></aside></div>`)}
function getMeds(){return JSON.parse(localStorage.getItem('medisafe_meds')||'null')||[{name:'Metformin',dose:'500 mg · Twice a day',tag:'Diabetes'},{name:'Amlodipine',dose:'5 mg · Once a day',tag:'Blood pressure'},{name:'Paracetamol',dose:'500 mg · As needed',tag:'Pain / Fever'}]}
function saveMeds(m){localStorage.setItem('medisafe_meds',JSON.stringify(m))}
function medicines(){shell('medicines',`<div class="content-head"><div><span class="eyebrow">MEDICINE LIBRARY</span><h1>My Medicines</h1><p>Search the demo medicine catalogue and manage your cabinet.</p></div><button class="btn" id="addMed">＋ Add Medicine</button></div><div class="search-box"><input id="medSearch" placeholder="Search medicine, composition or category"><button>Search</button></div><div id="medicineResults" class="medicine-grid"></div>`);renderMeds(DATA);document.getElementById('medSearch').oninput=e=>renderMeds(DATA.filter(x=>(x.name+' '+x.generic+' '+x.tag).toLowerCase().includes(e.target.value.toLowerCase())));document.getElementById('addMed').onclick=()=>{const name=prompt('Medicine name?');if(name){const m=getMeds();m.unshift({name,dose:'Dose not added',tag:'Custom'});saveMeds(m);toast('Medicine added to your cabinet');}}}
function renderMeds(list){document.getElementById('medicineResults').innerHTML=list.map(x=>`<article class="medicine-card"><div class="pill-icon">◉</div><h3>${esc(x.name)}</h3><span class="tag">${esc(x.tag)}</span><p>${esc(x.generic||x.dose||'Medicine information')}</p><small class="muted">${esc(x.manufacturer||'Your medicine cabinet')}</small><br><button class="btn btn-sm" style="margin-top:14px" onclick="toast('Medicine details opened for ${esc(x.name)}')">View details</button></article>`).join('')||'<div class="soft-card">No matching medicine found in the demo catalogue.</div>'}
function checker(){shell('checker',`<div class="content-head"><div><span class="eyebrow">SAFETY CHECK</span><h1>Interaction Checker</h1><p>Choose two medicines to see a prototype warning.</p></div></div><div class="checker-grid"><section class="soft-card"><div class="select-field"><label>Medicine 1</label><select id="m1"><option value="">Select medicine</option><option>Aspirin</option><option>Warfarin</option><option>Ibuprofen</option><option>Metformin</option><option>Glimepiride</option><option>Paracetamol</option></select></div><div class="select-field"><label>Medicine 2</label><select id="m2"><option value="">Select medicine</option><option>Aspirin</option><option>Warfarin</option><option>Ibuprofen</option><option>Metformin</option><option>Glimepiride</option><option>Paracetamol</option></select></div><button class="btn btn-block" id="checkBtn">Check interaction</button><p class="muted" style="font-size:12px;margin-top:15px">Prototype only — not a substitute for professional medical advice.</p></section><section class="soft-card"><span class="eyebrow">RESULT</span><div id="checkResult" class="result" style="margin-top:18px">Select two medicines and run the check.</div></section></div>`);document.getElementById('checkBtn').onclick=()=>{const a=document.getElementById('m1').value,b=document.getElementById('m2').value;if(!a||!b)return toast('Select both medicines');if(a===b)return showResult('Mild','The same medicine was selected twice. Please verify your entries.','warning');const key=[a,b].map(x=>x.toLowerCase()).sort().join('|'),r=interactions[key]||{level:'No major demo match',text:'No matching interaction is stored in this prototype dataset. This does not prove that the medicines are safe together.'};showResult(r.level,r.text,r.level==='Severe'?'danger':r.level==='Moderate'?'warning':'')}}
function showResult(level,text,cls=''){const r=document.getElementById('checkResult');r.className='result show '+cls;r.innerHTML=`<strong>${esc(level)}</strong><p>${esc(text)}</p>`;saveHistory(document.getElementById('m1').value+' + '+document.getElementById('m2').value,level)}
function getHistory(){return JSON.parse(localStorage.getItem('medisafe_history')||'null')||[]}
function saveHistory(pair,level){const h=getHistory();if(!pair)return;h.unshift({pair,level,date:new Date().toLocaleString()});localStorage.setItem('medisafe_history',JSON.stringify(h.slice(0,30)))}
function history(){const h=getHistory();shell('history',`<div class="content-head"><div><span class="eyebrow">SAFETY LOG</span><h1>Check History</h1><p>Review your recent medicine checks.</p></div><button class="btn btn-light" id="clearHistory">Clear history</button></div><div class="history-list">${h.length?h.map(x=>`<div class="history-row"><div><b>${esc(x.pair)}</b><small>${esc(x.date)}</small></div><span class="severity ${x.level==='Severe'?'severe':x.level==='Moderate'?'moderate':'mild'}">${esc(x.level)}</span></div>`).join(''):'<div class="history-row"><div><b>No checks yet</b><small>Your interaction checks will appear here.</small></div></div>'}</div>`);document.getElementById('clearHistory').onclick=()=>{localStorage.removeItem('medisafe_history');toast('History cleared');setTimeout(history,250)}}
function patient(){const meds=getMeds();shell('patient',`<div class="content-head"><div><span class="eyebrow">MY HEALTH SPACE</span><h1>Patient History</h1><p>Current and past medicine information.</p></div></div><div class="soft-card"><h3>Current Medicines</h3><div class="history-list">${meds.map((m,i)=>`<div class="history-row"><div><b>${esc(m.name)}</b><small>${esc(m.dose)}</small></div><span class="tag">${esc(m.tag)}</span></div>`).join('')}</div></div><div class="soft-card" style="margin-top:18px"><h3>Health Notes</h3><textarea id="healthNotes" rows="5" style="width:100%;border:1px solid var(--line);border-radius:13px;padding:13px" placeholder="Add a private note for your prototype...">${esc(localStorage.getItem('medisafe_notes')||'')}</textarea><button class="btn" id="saveNotes" style="margin-top:12px">Save notes</button></div>`);document.getElementById('saveNotes').onclick=()=>{localStorage.setItem('medisafe_notes',document.getElementById('healthNotes').value);toast('Notes saved locally')}}
function profile(){const p=getProfile();shell('profile',`<div class="content-head"><div><span class="eyebrow">ACCOUNT</span><h1>My Profile</h1><p>Manage your basic profile information.</p></div></div><div class="profile-layout"><section class="soft-card profile-hero"><div class="profile-big">${esc((p.name||'G')[0].toUpperCase())}</div><h2>${esc(p.name)}</h2><p class="muted">${esc(p.email)}</p><div class="profile-links"><a href="patient-history.html">Medical information <b>›</b></a><a href="patient-history.html">Allergies <b>›</b></a><a href="settings.html">Privacy & security <b>›</b></a></div></section><section class="soft-card"><h3>Personal Information</h3><form id="profileForm"><div class="form-grid"><div class="field"><label>Full name</label><input id="pn" value="${esc(p.name)}"></div><div class="field"><label>Email</label><input id="pe" type="email" value="${esc(p.email)}"></div></div><div class="field" style="margin-top:15px"><label>Phone</label><input id="pp" placeholder="+91 ..."></div><button class="btn" style="margin-top:18px">Save changes</button></form></section></div>`);document.getElementById('profileForm').onsubmit=e=>{e.preventDefault();localStorage.setItem('medisafe_profile',JSON.stringify({name:document.getElementById('pn').value,email:document.getElementById('pe').value}));toast('Profile saved');setTimeout(profile,350)}}
function settings(){shell('settings',`<div class="content-head"><div><span class="eyebrow">PREFERENCES</span><h1>Settings</h1><p>Personalise your MediSafe AI experience.</p></div></div><div class="settings-list"><div class="setting-row"><div><b>Notifications</b><small>Show medicine check reminders</small></div><button class="toggle on" data-setting="notify"></button></div><div class="setting-row"><div><b>Compact mode</b><small>Use tighter spacing on dashboards</small></div><button class="toggle" data-setting="compact"></button></div><div class="setting-row"><div><b>Privacy mode</b><small>Reduce visible profile details</small></div><button class="toggle" data-setting="privacy"></button></div><div class="setting-row"><div><b>Theme</b><small>Use the calm green theme</small></div><button class="toggle on" data-setting="theme"></button></div></div><div class="soft-card" style="margin-top:18px"><h3>About MediSafe AI</h3><p class="muted">A frontend prototype inspired by your green capsule / healthcare visual direction. For production, connect a secure backend and verified medicine data source.</p><button class="danger" onclick="logout()">Log out</button></div>`);document.querySelectorAll('.toggle').forEach(b=>b.onclick=()=>{b.classList.toggle('on');toast('Setting updated')})}
const current=path();if(current==='home.html'||current===''){home()}else if(current==='medicines.html'){medicines()}else if(current==='checker.html'){checker()}else if(current==='history.html'){history()}else if(current==='patient-history.html'){patient()}else if(current==='my-profile.html'){profile()}else if(current==='settings.html'){settings()}